import { Button } from '../ui/Button';
import { useRouter } from 'next/navigation';
import { Accordion } from '../ui/Accordion';

const FAQSection = () => {
  const router = useRouter();

  const faqs = [
    {
      question: 'How does the cover letter generator work?',
      answer:
        'Our OpenAI-powered tool analyzes your resume and job description to create a personalized cover letter that highlights your relevant skills and experience.',
    },
    {
      question: 'Can I edit the generated cover letter?',
      answer:
        'Yes, you have full control to edit, customize, and fine-tune any cover letter generated by our tool.',
    },
    {
      question: 'How long does it take to generate a cover letter?',
      answer:
        'AI generates a professional cover letter in less than a minute, saving you hours of writing time.',
    },
  ];

  return (
    <section className="py-16 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-12">
          Frequently Asked Questions
        </h2>
        <div className="max-w-3xl mx-auto mb-10">
          <Accordion items={faqs} />
        </div>
        <div className="text-center">
          <Button onClick={() => router.push('/faq')}>More Questions</Button>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
