import React from 'react';
import { Button } from '../ui/Button';
import Link from 'next/link';
import Image from 'next/image';
import MaxWidthWrapper from './MaxWidthWrapper';

const HeroSection = () => {
  return (
    <div className="bg-slate-100 relative overflow-hidden pt-8">
      <MaxWidthWrapper>
        <div className="flex justify-between items-center w-full min-h-[67vh]">
          <div className="w-full md:w-1/2 text-left flex flex-col items-start z-10">
            <h1 className="text-5xl font-bold text-gray-900 mb-4">
              Generate your perfect cover letter <br />
              in seconds
            </h1>
            <p className="text-xl text-gray-500 mb-6">
              Transform your job applications with personalized cover letters
              generated by AI.
            </p>
            <div className="flex gap-4">
              <Link href="/create/upload-cv">
                <Button size="lg" className="text-lg px-10 py-3">
                  Get Started
                </Button>
              </Link>
            </div>
          </div>
          <div className="absolute right-[-4%] bottom-[-33%] md:w-[60%] flex items-center justify-center">
            <Image
              alt="Example Cover Letter"
              src={'/exampleCoverLetter.png'}
              width={500}
              height={900}
              className="shadow-xl transform rotate-1"
              priority
            />
          </div>
        </div>
      </MaxWidthWrapper>
    </div>
  );
};

export default HeroSection;
