'use client';

import { Accordion } from '../../components/ui/Accordion';

const FAQPage = () => {
  const faqs = [
    {
      question: 'How does the cover letter generator work?',
      answer:
        'Our AI-powered tool analyzes your resume and job description to create a personalized cover letter that highlights your relevant skills and experience.',
    },
    {
      question: 'Can I edit the generated cover letter?',
      answer:
        'Yes, you have full control to edit, customize, and fine-tune any cover letter generated by our tool.',
    },
    {
      question: 'How long does it take to generate a cover letter?',
      answer:
        'Our AI generates a professional cover letter in less than a minute, saving you hours of writing time.',
    },
    {
      question: 'Is my information secure?',
      answer:
        'Yes, we take data privacy seriously. All your information is encrypted and we never share your personal data with third parties.',
    },
    {
      question: 'What format can I download my cover letter in?',
      answer:
        'You can download your cover letter in PDF, Word (.docx), or plain text format.',
    },
    {
      question: 'Can I create multiple versions of my cover letter?',
      answer:
        'Yes, you can create unlimited versions of your cover letter, each tailored to different job applications.',
    },
    {
      question: 'Do you offer any templates?',
      answer:
        'Yes, we provide a variety of professional templates that you can choose from to match your style and industry.',
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50 py-16">
      <div className="max-w-3xl mx-auto px-4">
        <h1 className="text-4xl font-bold text-center mb-12">
          Frequently Asked Questions
        </h1>
        <Accordion items={faqs} />
      </div>
    </div>
  );
};

export default FAQPage;
